# Generated by Django 5.1.1 on 2025-01-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_addwarehouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billimage',
            name='image',
            field=models.ImageField(upload_to='bill_photo/'),
        ),
        migrations.AlterField(
            model_name='topwarehouse',
            name='ranking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topwarehouse',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
    ]
