# Generated by Django 5.1.1 on 2025-01-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_billimage_image_alter_topwarehouse_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topwarehouse',
            name='ranking',
            field=models.IntegerField(unique=True),
        ),
    ]
