# Generated by Django 5.1.1 on 2025-01-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_topwarehouse_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topwarehouse',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
