# Generated by Django 5.1.1 on 2025-01-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_topwarehouse_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addwarehouse',
            name='price',
        ),
    ]
