# Generated by Django 5.1.1 on 2025-01-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_addwarehouse_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='price',
        ),
    ]
