# Generated by Django 5.1.1 on 2025-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menu_items/')),
                ('category', models.CharField(choices=[('Buff', 'Buff'), ('Chicken', 'Chicken'), ('Veg', 'Veg'), ('Mutton', 'Mutton')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
